In [1]:
import numpy as np
import mbuild as mb

from grits import CG_System
from grits.utils import amber_dict

/Users/stephaniemccallum/miniforge3/envs/grits/lib/python3.12/site-packages/mdtraj/formats/__init__.py:13: DeprecationWarning: 'xdrlib' is deprecated and slated for removal in Python 3.13
  from mdtraj.formats.trr import TRRTrajectoryFile
/Users/stephaniemccallum/miniforge3/envs/grits/lib/python3.12/site-packages/foyer/forcefield.py:33: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import iter_entry_points, resource_filename
/Users/stephaniemccallum/miniforge3/envs/grits/lib/python3.12/site-packages/pkg_resources/__init__.py:3144: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/Users/stephaniemccallum/miniforge3/envs/grits/li

In [2]:
PPS_smiles = "c1ccc(S)cc1"
a = mb.load(PPS_smiles, smiles=True)
# a.visualize().show()

In [3]:
gsdfile = "/Users/stephaniemccallum/Desktop/cmelab/forks/grits/pps_trajectory_kT_2.0.gsd"
system = CG_System(
    gsdfile,
    add_hydrogens=True,
    beads={"_A": PPS_smiles},
    conversion_dict=amber_dict,
)

Added 6 hydrogens.


/Users/stephaniemccallum/Desktop/cmelab/forks/grits/grits/coarsegrain.py:192: UserWarning: Some atoms have been left out of coarse-graining!
  warn(f"Some atoms have been left out of coarse-graining!")


In [4]:
cg_gsd = "PPS-cg.gsd"
system.save(cg_gsd)

In [5]:
import gsd.hoomd

traj = gsd.hoomd.open(gsdfile)
snap = traj[-1]

In [6]:
inds = [0, 1, 2, 3]

In [7]:
np.add.reduce(snap.log["particles/md/pair/LJ/forces"][inds])

array([-0.58440879, -0.72004115, -0.20885618])

In [8]:
print(snap.log["particles/md/pair/LJ/forces"])

[[-0.59678146 -0.7094508  -0.20883539]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 ...
 [-0.23439395 -0.89780405 -0.28628996]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]


In [9]:
snap.particles.velocity

array([[ 0.46751893, -0.4557764 ,  1.5517997 ],
       [ 1.2661922 ,  2.2942452 ,  2.3974137 ],
       [ 0.99841857, -0.54276377, -0.38419962],
       ...,
       [-0.16005144,  0.94953936, -1.093895  ],
       [ 0.6594045 , -1.5998036 , -1.1851496 ],
       [-0.8315832 ,  1.2608055 ,  0.19617926]], dtype=float32)

In [10]:
dir(snap)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slotnames__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_valid_state',
 'angles',
 'bonds',
 'configuration',
 'constraints',
 'dihedrals',
 'impropers',
 'log',
 'pairs',
 'particles',
 'state',
 'validate']